In [2]:
import numpy as np
import scipy
"""Link to the numpy docs: https://docs.scipy.org/doc/numpy-1.13.0/reference/"""

'Link to the numpy docs: https://docs.scipy.org/doc/numpy-1.13.0/reference/'

Lets solve a few basic numpy problems

In [10]:
def get_range(start, end, step):
    """Return an array of given range with specific step"""
    arr = np.arange(start, end, step)
    return(arr)


#get_range(1,10,2)



In [25]:
def new_shape(old_array, new_shape):
    """Return an array of given shape"""
    #check if array can be reshaped to given dimensions
    if old_array.size != (lambda a: a[0]*a[1])(new_shape):
        return None
    
    #define the function to reshape the array & return
    return old_array.reshape(new_shape)
    
#old_arr = np.array([1,2,3,4,5,6])
#new_arr = new_shape(old_arr, (2,3))
#print(new_arr)

new_arr = [[1 2 3]
 [4 5 6]]


In [49]:
def reverse_array(old_array):
    """Return the reversed array"""
    #initialize array
    
    #define function to reverse array
    
    #return the array
    return(np.flip(old_array, 1))
arr=np.array([[1,2,3,4],[5,6,7,8]])
reverse_array(arr)

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [51]:
def stack_lists(lists):
    """Return an array containing lists stacked horizontally"""
    #initialize array
    
    #define function to return array with stacked lists given whether arrays to be stacked horizontally or vertically
    
    #return the array
    return(np.hstack(lists))


In [34]:
def get_trignometric_values(angles):
    """Return an array containing sine, cosine and tangent values of the given angle stacked horizontally"""
    #initialize array
    
    #define sine function
    sin = np.sin(angles)
    #define cosine function
    cos = np.cos(angles)
    #define tangent function
    tan = np.tan(angles)
    #define function to return array with stacked lists
    trigs=[sin,cos,tan]
    arr=np.hstack(trigs)
    #return the array
    return(arr)


array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ,  0.54030231,
        -0.41614684, -0.9899925 , -0.65364362,  1.55740772, -2.18503986,
        -0.14254654,  1.15782128],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.28366219,
         0.96017029,  0.75390225, -0.14550003, -3.38051501, -0.29100619,
         0.87144798, -6.79971146]])

In [52]:
def invert_array(array):
    """Return the pseudo inverse of the given array; read more about pseudo inverse at: 
    https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse"""
    #define function to invert array
    inv = np.linalg.pinv(array)
    #return the array
    return(inv)

In [53]:
def flatten_array(array):
    """Return the flattened array"""
    #define function to flatten array
    
    #return the array
    return(array.flatten())

In [4]:
def add_noise(array, mean, std):
    """Add gaussian noise with given mean and standard deviation; read more about the normal distribution at:
    https://en.wikipedia.org/wiki/Normal_distribution"""
    #define function to add noise with the given mean and standard deviation
    
    #return the array
    return(np.random.noise(mean, std, array.size))

In [4]:
def expand_array(array, axis):
    """Return an array expanded along the column"""
    #define function to expand array
    
    #return the array
    return(np.expand_dims(array, axis))

In [1]:
def sigmoid_fn(array):
    """Return an array with the sigmoid values"""
    #define sigmoid function 
    return list(map(lambda x: 1 / (1 + np.exp(-x)), array))
    #return the array
    
    #return(new_arr)

#arr=np.array([[1,2,3,4],[5,6,7,8]])
#sigmoid_fn(arr)

In [3]:

def get_means(array):
    means=[]
    """Return arithmetic mean, geometric mean, harmonic mean and log means in a column array"""
    #define function for arithmetic mean
    means.append(np.mean(array))
    #define function for geometric mean
    means.append(scipy.stats.gmean(array)) 
    #define function for harmonic mean
    means.append(scipy.stats.hmean(array)) 
    #define function for log means
    means.append(np.log(array).mean())
    #stack the means in an array
    arr=np.hstack(means)
    #return the array
    return(arr)
#arr=np.array([1,2,3,4])
#get_means(arr)

In [39]:
def return_count(array, threshold):
    """Return the number of elements above the threshold in an array"""
    #define function to count the number of elements above the threshold
    
    #return the value
    return(array[np.where(array > threshold)])
#arr=np.array([1,2,3,4])
#return_count(arr,2)

array([3, 4])

In [61]:
def column_sum(array, column_no):
    """Return the sum of all the elements in a column of the array"""
    #check if column exists in array, else return(np.nan)
    try:
        return(np.sum(array[column_no]))
    except IndexError:
        return(np.nan)
    #define function to return the sum of elements in the given column
    
    #return the value
    
#arr=np.array([[1,2,3,4],[1,2,3,4]])
#column_sum(arr,1)



10

In [19]:
def row_sum(array, row_no):
    """Return the sum of all the elements in a row of the array"""
    #check if row exists in array, else return(np.nan)
    
    #define function to return the sum of elements in the given row
    
    #return the value
    try:
        return(np.sum(array[row_no]))
    except IndexError:
        return(np.nan)

In [65]:
def check_diag(array):
    """Return True if the matrix is diagonal"""
    #define function to chweck if the matrix is diagonal
    if np.array_equal(np.diag(np.diag(array)), array):
        return True
    return False
    #return True/False
